### ISSUE TITLE
Add Nightly Releases link to Downloads page

### ISSUE THREAD

**Issue by RodneyBaker** [opentoonz/opentoonz.github.io#57]
Because Opentoonz official releases are expected to be annual users often are unaware of interim releases that may address their needs, fix bugs and introduce new features.

Adding a link to Nightly Releaese on the downloads page will help highlight that Opentoonz is continuously improved and point users to where they can test the latest releases.

What the link might look like on the current page:

![Add Nightly releases link to Download page](https://user-images.githubusercontent.com/2576432/69923313-7bd68780-1469-11ea-825a-27db600b6237.png)

**Comment by RodneyBaker** [comment]
actual html used to create above mockup is attached...

filename has been renamed with '_nightlies' added and .html extension is changed to .txt for purpose of uploading.
[opentoonz_nightlies.txt](https://github.com/opentoonz/opentoonz.github.io/files/3908977/opentoonz_nightlies.txt)

Note:  This does not address updating pages for other languages although placement of link and text would be the same.

**Comment by DarrenTAnims** [comment]
Is this a possibility to add @shun-iwasawa?

The exact format of the links on screen isn't important to match the above, but the words need to be clear enough to prompt users that a newer version is available. And perhaps to list or have a link to, important bugs that are fixed by it.

It would really help the users and also our support time as users are downloading effectively broken builds and we're getting the same bug reports over and over for something that was fixed months ago.

**Comment by gab3d** [comment]
I think it'd be good to have, just as Blender official download page has links to their nightlies.
https://www.blender.org/download/

![imagen](https://user-images.githubusercontent.com/18104091/111549297-b5183100-875a-11eb-81cf-f2826cf71909.png)

**Comment by shun-iwasawa** [comment]
I'll add the link after releasing V1.5. Thanks!
