### ISSUE TITLE
How can I translate the OpenToonz website into Persian?

### ISSUE THREAD

**Issue by pikhosh** [opentoonz/opentoonz.github.io#63]
Hello! I wanted to ask how I can translate the OpenToonz website into **Persian**? Like the **Spanish** translation.

**Comment by shun-iwasawa** [comment]
You can post a pull request for that just like other repositories.

Please let me know if I might be able to help you with.
I think I can help you to write html/css sources based on your translation text (if you would like), but I'm not sure if I can help making title images like [this](https://opentoonz.github.io/e/img/point_sttl.png) as I don't have any nice Persian font.

**Comment by pikhosh** [comment]
> You can post a pull request for that just like other repositories.
> 
> Please let me know if I might be able to help you with.
> I think I can help you to write html/css sources based on your translation text (if you would like), but I'm not sure if I can help making title images like [this](https://opentoonz.github.io/e/img/point_sttl.png) as I don't have any nice Persian font.

Hello! Thanks for your answer 😄

I can translate texts and all images into Persian, but I have very little knowledge of "HTML" and "CSS" (which of course I can learn)

The point is; That I used the "How to contribute" File to translate the documentation, which made it very easy for me; But I do not know how to use the Website repository files for translation; Can you explain the process to me?

**Comment by shun-iwasawa** [comment]
Since the website is updated not so frequent than the document, currently the website does not use any intermediate files for translation. i.e. Pages in each language are written in separate files in different folders. 

I think you can start by copying the folder `./e/` (Containing all files for English pages) and renaming it to `./fa/` , then replace all English texts to Persian ones. 
After finishing the translation, add `Persian` button to the [head of each page](https://github.com/opentoonz/opentoonz.github.io/blob/master/e/index.html#L168-L173) for changing the languages.

**Comment by pikhosh** [comment]
Thanks for your help 😊 I'm going to see what I can do; I hope it will be useful!

**Comment by pikhosh** [comment]
@shun-iwasawa I had a question: Can I implement custom font for Persian pages? Because I did not see other languages do that

**Comment by shun-iwasawa** [comment]
@piki-shabpareh 
Yes you can. 
(I'm not so familiar with implementing the custom font, though :-) )
